version: "3.3"

services:
  vr_app_be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vr_app_be_container
    image: vr_app_be_image
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: vr_app_db_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5436:5432"
    volumes:
      - vr_app_db_volumes:/var/lib/postgresql/data

volumes:
  vr_app_db_volumes:
